<?php
/** @var \WolfSellers\ReferredUsers\Block\Account\Create $block */
?>

<form action="<?= $block->getUrl('referrals/index/save') ?>" method="post">
    <?= $block->getBlockHtml('formkey') ?>
    <div class="field">
        <label for="first_name"><?= __('Name') ?></label>
        <input type="text" name="first_name" id="first_name" required>
    </div>
    <div class="field">
        <label for="last_name"><?= __('Last Name') ?></label>
        <input type="text" name="last_name" id="last_name" required>
    </div>
    <div class="field">
        <label for="email"><?= __('Email') ?></label>
        <input type="email" name="email" id="email" required>
    </div>
    <div class="field">
        <label for="phone"><?= __('Phone') ?></label>
        <input type="text" name="phone" id="phone">
    </div>
    <div class="actions-toolbar">
        <button type="submit" class="action primary">
            <?= __('Save') ?>
        </button>
    </div>
</form>
